# Numerical Algorithms: Homework 2
Please **submit this Jupyter notebook through Canvas** no later than **Monday November 11, 8:59**, before the start of the lecture.

Homework is in **groups of two**, and you are expected to hand in original work. Work that is copied from another group will not be accepted.

-----
# Exercise 0
In the box below, write down the names + student ID of the people in your group.

Name1: Julien Fer <br>
Name2: Wiebe Jelsma<br>
Student_number1: 10649441<br>
Student_number2: 12468223 <br>

-----
# Exercise 1
Let $A$ be the matrix

$$
A = \begin{bmatrix} -1 & \alpha & 1 \\ 2 & 1 & -1 \\ \alpha & 0 & 1 \end{bmatrix}.
$$

## (a) 
For which values of $\alpha$ is $A$ singular? Explain your answer.

Explain your answer, using $\LaTeX$, in this cell.
Explain your answer, using $\LaTeX$, in this cell.
Again, we rounded our answers to 4 decimals. <br><br>
To find out if A is singular, we need to check the determinant. If the determinant is equal to 0, A is singular. <br>
We get this by the following equation: <br>
$A_{11}$ $* (A\tiny{22}$$ * A\tiny{33}$$ - A\tiny{23}$$ * A\tiny{32}$$) - A\tiny{12}$$ * (A\tiny{21}$$ * A\tiny{32}$$ - A\tiny{22}$$ * A\tiny{31}$$) + A\tiny{13}$$ * (A\tiny{21}$$ * A\tiny{32}$$ - A\tiny{22}$$ * A\tiny{31}$$)  $ <br>
We fill this in with numbers: <br>
$-1* (1*1 - -1*0) - \alpha * (2*1 - -1*\alpha) + 1 * (2*0 - 1*\alpha) $ <br>
This results in:
$ -1* (1) - \alpha * (2+ \alpha) + 1 * (-\alpha)$ <br>
We get the following equation:
$-1 -2\alpha - \alpha^2 - \alpha $
The determinant needs to be 0 for A to be singular, so we set the equation to be 0. We get <br>
$-1 -2\alpha - \alpha^2 - \alpha = 0$ <br>
We rewrite it to: $-\alpha^{2} -2\alpha -\alpha -1 = 0 $. This can be written down as: <br>
$\alpha^2 + 2\alpha + \alpha + 1 = 0 $
Thus, $\alpha$ needs to be either $-3.8196e^{-1}$ or $-2.6180$ for the matrix A to be singular

-----
# Exercise 2

## (a) 
Investigate what happens when Gaussian elimination with partial pivoting is used on a matrix of the following form

\begin{equation}
\begin{bmatrix}
1 & 0 & 0 & 0 & 1 \\
-1 & 1 & 0 & 0 & 1 \\
-1 & -1 & 1 & 0 & 1 \\
-1 & -1 & -1 & 1 & 1 \\
-1 & -1 & -1 & -1 & 1
\end{bmatrix}.\label{eq:mat} \tag{1}
\end{equation}

State the resulting matrix $U$. Do the entries grow? What is the growth factor? (Note that this part does not require any computations/code.)


In [1]:
import pprint
import scipy
import scipy.linalg   # SciPy Linear Algebra Library
A = scipy.array([ [1 , 0 , 0 , 0 , 1], [-1 , 1 , 0 , 0 , 1], [-1 , -1, 1 , 0 , 1], [-1 , -1 , -1 , 1 , 1], [-1 , -1, -1 , -1 , 1] ])
P, L, U = scipy.linalg.lu(A)
print("A:")
pprint.pprint(A)

print("P:")
pprint.pprint(P)

print("L:")
pprint.pprint(L)

print("U:")
pprint.pprint(U)

A:
array([[ 1,  0,  0,  0,  1],
       [-1,  1,  0,  0,  1],
       [-1, -1,  1,  0,  1],
       [-1, -1, -1,  1,  1],
       [-1, -1, -1, -1,  1]])
P:
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])
L:
array([[ 1.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  0.,  0.,  0.],
       [-1., -1.,  1.,  0.,  0.],
       [-1., -1., -1.,  1.,  0.],
       [-1., -1., -1., -1.,  1.]])
U:
array([[ 1.,  0.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  2.],
       [ 0.,  0.,  1.,  0.,  4.],
       [ 0.,  0.,  0.,  1.,  8.],
       [ 0.,  0.,  0.,  0., 16.]])


Explain your answer, using $\LaTeX$, in this cell. You can write a matrix like this: $\begin{bmatrix}
\alpha & \beta \\ 
\beta^\top & -\gamma
\end{bmatrix}$.
We make use of partial pivoting because we only exchange rows. In exercise b we will use complete pivoting, and for this we will make use of exchanging row and columns. <br>
$A_{x} = LU_{x} = b$ <br>
After using partial pivoting, we found the following matrix. <br>
\begin{equation}
\begin{bmatrix}
1 & 0 & 0 & 0 & 1 \\
0 & 1 & 0 & 0 & 2 \\
0 & 0 & 1 & 0 & 4 \\
0 & 0 & 0 & 1 & 8 \\
0 & 0 & 0 & 0 & 16
\end{bmatrix}.\label{eq:matrix} \tag{2}
\end{equation}


We can indeed see that the entries grow, with a growth rate of 16.

## (b) 
What happens if complete pivoting is used instead? State the resulting matrix $U$. What is the growth factor in this case? (This part doesn't require any computations/code.)


Explain your answer, using $\LaTeX$, in this cell.
Now we will use complete pivot. This means that we can change both rows and columns.
The outcome is different. We get a different growth factor, and differes results in matrix $U$. 
\begin{equation}
\begin{bmatrix}
1 & 1 & 0 & 0 & 0 \\
0 & 2 & 1 & 0 & 0 \\
0 & 0 & -2 & 1 & 0 \\
0 & 0 & 0 & -2 & 1 \\
0 & 0 & 0 & 0 & -2
\end{bmatrix}.\label{eq:matrix} \tag{2}
\end{equation} <br>
We can see that the growth factor is 2. The growth factor is always an absolute value.

## (c) 
Write a function that creates $n \times n$-matrices of this form $(1)$, for any given size $n$. Test it by generating a matrix for $n = 8$.


In [15]:
import sympy
import numpy as np
n = 8
C = np.eye(n)

for i in range(n):
    C[i,0:i] = -1
    C[i, n-1] = 1
    
pprint.pprint(C)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [-1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.],
       [-1., -1.,  1.,  0.,  0.,  0.,  0.,  1.],
       [-1., -1., -1.,  1.,  0.,  0.,  0.,  1.],
       [-1., -1., -1., -1.,  1.,  0.,  0.,  1.],
       [-1., -1., -1., -1., -1.,  1.,  0.,  1.],
       [-1., -1., -1., -1., -1., -1.,  1.,  1.],
       [-1., -1., -1., -1., -1., -1., -1.,  1.]])


## (d) 
Use Gaussian elimination with partial pivoting to solve equations of the form $Ax = b$, with $A$ the matrix for $n = 60$, choosing right-hand-side vectors so that the solution is known.

Do you observe that the results are useless because of the large growth factor? 

It is possible that you do not observe this, because the integer entries of $A$ may prevent rounding errors from occurring. If so, modify the problem slightly so that the growth factor is the same or nearly so and catastrophic rounding errors really do occur. 

State your computational results clearly to make your point.


Note: This artificially contrived system illustrates the worst-case growth factor cited in section 2.4.5 of the book, and is not indicative of the usual behavior of Gaussian elimination with partial pivoting.

In [3]:
# Write your implementation in this cell
# Use comments to explain your code

Explain your answer, using $\LaTeX$, in this cell.

-----
# Exercise 3

## (a) 
If $u$ and $v$ are nonzero $n$-vectors, prove that the $n×n$ outer product matrix $uv^\top$ has rank one.

Explain your answer, using $\LaTeX$, in this cell. <br>
According to the Numerical algorithms book, An n×n matrix A is said to be nonsingular if it satisfies any one of the following equivalent conditions: 
1. A has an inverse (i.e., there is an n × n matrix, denoted by A−1, such that AA−1 = A−1A = I, the identity matrix). <br>
2. $det(A) \neq 0$ (i.e., the determinant of A is nonzero). <br>
3. rank(A) = n (the rank of a matrix is the maximum number of linearly independent rows or columns it contains). <br>
4. For any vector $z \neq 0, Az \neq 0 $(i.e., A annihilates no nontrivial vector). <br>
We assume $u,v \neq 0$ <br>
$v_{i} = i,...,n$ and $u_{i} = i,...,m$. Therefore, $uv^T$ has the dimensions of $M x N$. <br>
We see that $uv^T$ is <br>

\begin{align}
  uv^T &= \begin{bmatrix}
         u_{1} \\
         u_{2} \\
         \vdots \\
         u_{m}
       \end{bmatrix}
         \begin{bmatrix}
  v_{1}, v_{2}, ..., v_{n}
  \end{bmatrix}
\end{align}
<br>

The columns of $uv^T$ are dependent to the non-zero columns, because the columns of $uv^T$ are multiples of the first non-zero column of $v$. 
In other words, the $rank(uv^T)$ is determined by the $max(rank(u), rank(v))$ which equals 1.


## (b)
If $A$ is an $n×n$ matrix such that $\mathop{rank}(A) = 1$, prove that there exist nonzero $n$-vectors $u$ and $v$ such that $A = uv^\top$.

Explain your answer, using $\LaTeX$, in this cell. <br>
$rank(A) = 1$, so that means $u$ and $v$ have to be nonzero n-factors. When writing $uv^T$, we get: \begin{align}
   \begin{bmatrix}
         u_{1} \\
         u_{2} \\
         \vdots \\
         u_{m}
       \end{bmatrix}
         \begin{bmatrix}
  v_{1}, v_{2}, ..., v_{n}
  \end{bmatrix}
\end{align}
<br>
If $u$ and $v$ are zero n-factors, it would not be possible to get a 1 for $rank(A)$. Therefore, because $rank(A) = 1$, $u$ and $v$ have to be nonzero n-factors. By multiplying $u$ with $v^T$ we get matrix A. We have to keep in mind that the columns of $uv^T$ are dependent on one independent column. This independent column builds up the matrix $A$ itself. Therefore, multiplying this independent column with $v^T$, we will get matrix $A$. 